AllCops:
  DisplayCopNames: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: true

Style/SignalException:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 200
